CREATE TABLE Productos (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Descripcion VARCHAR(50) NOT NULL,
    Precio DECIMAL(6,2) NOT NULL,
    Categoria VARCHAR(50) NOT NULL
);
CREATE TABLE Tickets (
    ID VARCHAR(100) NOT NULL PRIMARY KEY,
    Total DECIMAL(10,2) NOT NULL,
    Payload VARCHAR(2000) NOT NULL,
    Estado VARCHAR(50) NOT NULL,
    FechaCreacion DATETIME
);