CREATE TABLE Productos (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Descripcion VARCHAR(50) NOT NULL,
    Precio DECIMAL(6,2) NOT NULL,
    Categoria VARCHAR(50) NOT NULL
);
CREATE TABLE Tickets (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,  
    ID_TRACKEO INT NOT NULL,
    Total DECIMAL(6,2) NOT NULL,
    Payload VARCHAR(200) NOT NULL,
    Estado VARCHAR(50) NOT NULL,
    FechaCreacion DATETIME DEFAULT NOW(),  
    UNIQUE (ID_TRACKEO)  
);