<SecondScreen>:
    name: 'second_view'
    canvas.before:
        Color: 
            rgba: (203/255, 191/255, 168/255, 1)
        Rectangle:
            pos: self.pos
            size: self.size

    FloatLayout:
        Image:
            source: 'logo.png' 
            size_hint: None, None
            size: dp(100), dp(100) 
            pos_hint: {'center_x': 0.5, 'top': 1}  
            allow_stretch: True 

        MDTextField:
            id: input_trackeo
            hint_text: "Ingrese Código Rastreo"
            helper_text: 'ID del Cliente'
            helper_text_mode: 'on_focus'
            font_size: '20pt'
            size_hint_y: None
            size_hint_x: None
            width: dp(300)
            height: 50
            pos_hint: {'center_x': 0.5, 'center_y': 0.8}
            text_color: (0, 0.157, 0.176, 1)
            line_color_normal: (0.796, 0.749, 0.659, 1)
            line_color_focus: (0, 0.157, 0.176)
            elevation: 0
            multiline: False

        MDRaisedButton:
            text: "Buscar"
            pos_hint: {'center_x': 0.75, 'center_y': 0.8}
            size_hint: None, None
            size: dp(80), dp(40)
            on_release: root.obtener_datos_cliente(root.ids.input_trackeo.text)
        
        MDRaisedButton:
            text: 'Autorizando'
            font_size: '20pt'
            underline: True
            size_hint_y: None
            pos_hint: {'center_x': 0.5, 'center_y': 0.6}
            elevation: 0
            on_release: root.consultar_ticket(self.text)
        
        MDRaisedButton:
            text: 'Armando pedido'
            font_size: '20pt'
            underline: True
            size_hint_y: None
            pos_hint: {'center_x': 0.5, 'center_y': 0.5}
            elevation: 0
            on_release: root.consultar_ticket(self.text)
        
        MDRaisedButton:
            text: 'En camino'
            font_size: '20pt'
            underline: True
            size_hint_y: None
            pos_hint: {'center_x': 0.5, 'center_y': 0.4}
            elevation: 0
            on_release: root.consultar_ticket(self.text)
        
        MDRaisedButton:
            text: 'Estamos en su domicilio'
            font_size: '20pt'
            underline: True
            size_hint_y: None
            pos_hint: {'center_x': 0.5, 'center_y': 0.3}
            elevation: 0
            on_release: root.consultar_ticket(self.text)
        
        MDRaisedButton:
            text: 'Pedido Entregado'
            font_size: '20pt'
            underline: True
            size_hint_y: None
            pos_hint: {'center_x': 0.5, 'center_y': 0.2}
            elevation: 0
            on_release: root.consultar_ticket(self.text)

        MDLabel:
            id: nombre_label
            text: f"Pedido para: {root.nombre_cliente}"  # Esto se actualizará al obtener los datos
            font_size: '18pt'
            size_hint_y: None
            height: 50
            pos_hint: {'center_x': 0.5, 'top': 0.15}

        MDLabel:
            id: direccion_label
            text: f"Dirección: {root.direccion_cliente}"  # Esto se actualizará al obtener los datos
            font_size: '18pt'
            size_hint_y: None
            height: 50
            pos_hint: {'center_x': 0.5, 'top': 0.1}
